### ISSUE TITLE
[BUG] Tasks assigned by others not populating correctly.

### ISSUE THREAD

**Issue by illisan** [slackapi/tasks-app#61]
### Is there an existing issue for this?

- [X] I have searched for any related issues and avoided creating a duplicate issue.

### Have you read our code of conduct?

- [X] I have read and agree to the code of conduct

### Current Behavior

Creating a task and assigning it to another user will not upload the task to the user's App Home right away. New assigned tasks will only appear after a current open task is marked as complete.

### Expected Behavior

Once a user creates a task and assigns it to another user. The assigned user should receive a DM (this currently works) and the new task should appear under Open tasks on their App Home.

### Steps To Reproduce

1. On task-assign-user branch run app
2. Open modal to create new task
3. Fill out all input fields and assign task to another user
4. As the assigned user, open your App Home
5. There will be no new task but you would've received a DM notifying you about new task
6. As assigned user, check off a task from your Open tasks view, you should see the new task populate
7. If you have no tasks to check off there is no apparent way to retrieve the newly assigned task.

### Environment

```markdown
- OS: 
- Language version:
```

**Comment by colmdoyle** [comment]
The bug here was that we didn't reload the app home when a new task was assigned to someone other than the creator. When #62 is merged into #50 and that is then merged into `main`, we should be all good to close this.
